### ISSUE TITLE
Fix damage done by DA

### ISSUE THREAD

**Issue by seanpeters86** [seanpeters86/bfa-shadow-priest#11]
Dark ascension is bugged and is currently doing 20% too much damage.

https://cdn.discordapp.com/attachments/234014456584077313/459455077330190336/image.png

> Kaesebrezen - Today at 3:31 PM
the damage thing is because the shadowpriest aura hasn't dark ascension listed on it
because ingame it's treated fully as a void eruption cast

```
da_mul 1.088 vs da_mul 1.36
```

1st commit: https://github.com/simulationcraft/simc/commit/c0ece41a750b41bbdf96c331ea45d5830cb52bde

**Comment by lgkern** [comment]
Fixed by https://github.com/simulationcraft/simc/commit/cfc0fbc2db0befbb7a1ee5747f8a15a3b9eafaeb
