### ISSUE TITLE
 Create Uldir composite spreadsheet

### ISSUE THREAD

**Issue by seanpeters86** [seanpeters86/bfa-shadow-priest#40]
Created base sheet with simple weights from memory of the fights:

https://docs.google.com/spreadsheets/d/1pQBVcveJ_vN2_vj-KUFBZ1zBwsheldrmUmj5KmBSiw8/edit?usp=sharing

**Comment by djriff** [comment]
Will likely be a holdover until we nail down actual boss fights in simc.

**Comment by seanpeters86** [comment]
Big Add - 1 add, lasts for 20s, 60s cooldown
Small Add(s) - 3 adds, lasts for 10s, 45s cooldown

Light Movement - moves 50 yards, 85s cooldown
Heavy Movement - moves 25 yards, 10s cooldown

**Comment by seanpeters86** [comment]
First iteration is done, throwing a new issue in the backlog to revisit again post-uldir launch https://github.com/seanpeters86/bfa-shadow-priest/issues/49
